# -*- coding: utf-8 -*-
"""Selamat Datang di Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import streamlit as st
import time

def wide_awake_lyrics_streamlit():
    st.title("Wide Awake - Katy Perry")
    st.markdown("---")

    # Placeholder untuk menampilkan lirik
    lyrics_placeholder = st.empty()

    # List of tuples: (line_to_print, time_to_wait_before_next_line)
    lyrics = [
        ("I'm wide awake", 2.0),
        ("I'm wide awake", 1.8),
        ("I'm wide awake", 2.0),
        ("Yeah, I was in the dark", 1.2),
        ("I was falling hard", 1.2),
        ("With an open heart", 1.5),
        ("I'm wide awake", 2.0),
        ("How did I read the stars so wrong?", 2.5),
        ("I'm wide awake", 2.0),
        ("And now it's clear to me", 1.5),
        ("That everything you see", 1.2),
        ("Ain't always what it seems", 1.5),
        ("I'm wide awake", 2.0),
        ("Yeah, I was dreaming for so long", 2.5),
        ("I wish I knew then what I know now", 2.0),
        ("Wouldn't dive in, wouldn't bow down", 2.0),
        ("Gravity hurts, you made it so sweet", 2.0),
        ("'Til I woke up on, on the concrete", 2.5),
        ("Falling from cloud nine", 1.0),
        ("Crashing from the high", 1.0),
        ("I'm letting go tonight", 1.0),
        ("Yeah, I'm falling from cloud nine", 1.5),
        ("I'm wide awake", 2.0),
        ("Not losing any sleep", 1.5),
        ("I picked up every piece and landed on my feet", 2.0),
        ("I'm wide awake", 2.0),
        ("Need nothing to complete myself, no", 2.5),
        ("I'm wide awake", 2.0),
        ("Yeah, I am born again", 1.5),
        ("Out of the lion's den", 1.2),
        ("I don't have to pretend", 1.5),
        ("And it's too late", 1.0),
        ("The story's over now, the end", 2.0),
        ("I wish I knew then what I know now", 2.0),
        ("Wouldn't dive in, wouldn't bow down", 2.0),
        ("Gravity hurts, you made it so sweet", 2.0),
        ("'Til I woke up on, on the concrete", 2.5),
        ("Falling from cloud nine", 1.0),
        ("Crashing from the high", 1.0),
        ("I'm letting go tonight", 1.0),
        ("I'm falling from cloud nine", 1.5),
        ("Thunder rumbling", 1.0),
        ("Castles crumbling", 1.0),
        ("I'm trying to hold on", 1.0),
        ("God knows that I tried", 1.0),
        ("Seeing the bright side", 1.0),
        ("But I'm not blind anymore", 2.0),
        ("I'm wide awake", 1.5),
        ("I'm wide awake", 1.5),
        ("I'm wide awake", 1.5),
        ("I'm wide awake", 1.5)
    ]

    for line, delay in lyrics:
        lyrics_placeholder.write(f"### {line}")
        time.sleep(delay)

wide_awake_lyrics_streamlit()